apiVersion: v1
kind: Service
metadata:
  name: {{ include "weather-frontend.fullname" . }}
  labels:
    {{- include "weather-frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "weather-frontend.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.image.containerPort }}
      protocol: TCP
      name: http
